
name: ci

on:
  push:
    branches:
      - 'main'
  pull_request: {}
  # allow manual runs:
  workflow_dispatch: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/tillitis/tkey-builder:5rc2
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          # fetch-depth: 0
          persist-credentials: false

      - name: Build
        run: go build -buildvcs=false

      - name: tests
        run: go test ./...
        
